---
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "PLACEHOLDER"  # CodeDeploy replaces this dynamically
        LoadBalancerInfo:
          ContainerName: "my-ecs-app-container"
          ContainerPort: 3000
