version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "my-ecs-app-repo"
    AWS_REGION: "ap-south-1"
    S3_BUCKET: "my-ecs-app-s3"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 202533504513.dkr.ecr.$AWS_REGION.amazonaws.com

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 202533504513.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 202533504513.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"my-ecs-app-container","imageUri":"202533504513.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $AWS_REGION $IMAGE_REPO_NAME $IMAGE_TAG > imagedefinitions.json

      - echo Uploading imagedefinitions.json to S3...
      - aws s3 cp imagedefinitions.json s3://$S3_BUCKET/imagedefinitions.json

      - echo Uploading appspec.yml to S3...
      - aws s3 cp appspec.yml s3://$S3_BUCKET/appspec.yml

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
  discard-paths: yes

