version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"  # Change this if your region is different
    ECR_REPOSITORY: "my-ecs-app-repo"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 123456789012.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 123456789012.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest -t 123456789012.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION .

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 123456789012.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY --all-tags
      - echo Writing image definitions file...
      - printf '[{"name":"my-ecs-container","imageUri":"123456789012.dkr.ecr.%s.amazonaws.com/%s:latest"}]' $AWS_REGION $ECR_REPOSITORY > imagedefinitions.json
      - echo Uploading imagedefinitions.json to S3...
      - aws s3 cp imagedefinitions.json s3://my-ecs-app-s3/imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

